config/routes.rb
Rails3::Application.routes.draw do
  resources :bill_details

  resources :events

  get "home/index"

  devise_for :users
  root :to => "home#index"

end

app/models/amount.rb
class Amount < ActiveRecord::Base
  attr_accessible :amount, :user_id,:bill_detail_id
  belongs_to :user
end

app/models/bill_detail.rb
class BillDetail < ActiveRecord::Base
  attr_accessible :date, :event, :location,:bill_detail_id,:amounts_attributes
  has_many :amounts
  accepts_nested_attributes_for :amounts
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :date, :description, :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:first_name,:last_name
  # attr_accessible :title, :body
  has_one :bill_detail
  has_one :amount
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bill_details_controller.rb
class BillDetailsController < ApplicationController
  before_filter :set_bill_detail, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @bill_details = BillDetail.all
    respond_with(@bill_details)
  end

  def show
    respond_with(@bill_detail)
  end

  def new
    @bill_detail = BillDetail.new
    respond_with(@bill_detail)
  end

  def edit
  end

  def create
    @bill_detail = BillDetail.new(params[:bill_detail])
    @bill_detail.save
    respond_with(@bill_detail)
  end

  def update
    @bill_detail.update_attributes(params[:bill_detail])
    respond_with(@bill_detail)
  end

  def destroy
    @bill_detail.destroy
    respond_with(@bill_detail)
  end

  private
    def set_bill_detail
      @bill_detail = BillDetail.find(params[:id])
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :set_event, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @events = Event.all
    respond_with(@events)
  end

  def show
    respond_with(@event)
  end

  def new
    @event = Event.new
    respond_with(@event)
  end

  def edit
  end

  def create
    @event = Event.new(params[:event])
    @event.save
    respond_with(@event)
  end

  def update
    @event.update_attributes(params[:event])
    respond_with(@event)
  end

  def destroy
    @event.destroy
    respond_with(@event)
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bill_details_helper.rb
module BillDetailsHelper
	def get_total_amount(bill_detail)
	  bill_detail.amounts.map(&:amount).sum
	end 	
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/bill_details/_form.html.erb
<%#= form_for(@bill_detail) do |f| %>
<%= nested_form_for @bill_detail do |f| %>
  <% if @bill_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill_detail.errors.count, "error") %> prohibited this bill_detail from being saved:</h2>

      <ul>
      <% @bill_detail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event %><br />
    <%= f.select :event, [ 'lunch', 'dinner', 'snacks', 'breakfast'], :prompt => 'Select One' %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div> 

  <div class="field">
    <%= f.fields_for :amounts do |amount_form| %>
      <%= amount_form.text_field :amount %>
      <%= amount_form.link_to_remove "Remove this amount" %>
      Payed by 
      <% User.all.each do |user| %>
        <li>
          <%= check_box_tag 'user_ids[]', user.id -%>
          <%= h user.first_name -%>
          <%= amount_form.hidden_field :user_id, :value => user.id %>
          <%#= text_field_tag "user_amount[]",amount %>
        </li>
      <% end %>
    <% end %>
    <p><%= f.link_to_add "Add more amount", :amounts %></p>
  </div> 



 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bill_details/edit.html.erb
<h1>Editing bill_detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill_detail %> |
<%= link_to 'Back', bill_details_path %>

app/views/bill_details/index.html.erb
<h1>Listing bill_details</h1>

<table>
  <tr>
    <th>Event</th>
    <th>Location</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bill_details.each do |bill_detail| %>
  <tr>
    <td><%= bill_detail.event %></td>
    <td><%= bill_detail.location %></td>
    <td><%= bill_detail.date %></td>
    <td><%= link_to 'Show', bill_detail %></td>
    <td><%= link_to 'Edit', edit_bill_detail_path(bill_detail) %></td>
    <td><%= link_to 'Destroy', bill_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bill detail', new_bill_detail_path %>

app/views/bill_details/new.html.erb
<h1>Add details here</h1>

<%= render 'form' %>

<%= link_to 'Back', bill_details_path %>

app/views/bill_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Event:</b>
  <%= @bill_detail.event %>
</p>

<p>
  <b>Location:</b>
  <%= @bill_detail.location %>
</p>

<p>
  <b>Date:</b>
  <%= @bill_detail.date %>
</p>
<p>
  <b>Total Amount :</b>
  <%= get_total_amount(@bill_detail) %>
</p>

<%= link_to 'Back', bill_details_path %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.name %></td>
    <td><%= event.description %></td>
    <td><%= event.date %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @event.name %>
</p>

<p>
  <b>Description:</b>
  <%= @event.description %>
</p>

<p>
  <b>Date:</b>
  <%= @event.date %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails3</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag :defaults, "nested_form" %>
  <%= csrf_meta_tags %>
</head>
<body >
<nav class="navbar navbar-inverse" role="navigation">	
	<ul class="nav nav-pills"> 
		<% if user_signed_in? %>
			<li> <%= link_to('Logout', destroy_user_session_path, :method => :delete) %> </li>
			<li> <%= link_to('Add Event', new_event_path) %> </li>
			<li> <%= link_to('Add Bill details', new_bill_detail_path) %> </li>
		<% else %>
			<li> <%= link_to('Login', new_user_session_path)  %> </li>
			<li> <%= link_to('Register', new_user_registration_path)  %> </li>
		<% end %>
	</ul>	
</nav>	
<div class="container">
  <div class="panel panel-default">	
    <%= yield %>
    <%#= yield :role_sidebar %>
    <%#= yield :role_main %>
  </div>  
</div>
</html>